"""Property-based fuzz tests for parameterize patch decoders (#119).

For every (module, parameter) declared by the loaded vocabulary, this
suite asserts three byte-level invariants on the patch function:

1. **Round-trip**: ``decode(patch(src, name=v)) == v`` for the patched
   field, modulo float precision.
2. **Idempotence**: ``patch(patch(src, name=v), name=v) == patch(src,
   name=v)``. Patching twice produces the same bytes.
3. **Size invariance**: ``len(patch(src, name=v)) == len(src)``. The
   output blob is always the declared module struct size.

Parameters are generated by Hypothesis within each parameter's declared
range; the source op_params blob comes from the corresponding manifest
entry's dtstyle (a real-world starting point, not a synthetic baseline).

Catches the class of byte-correctness bugs the manual unit tests don't:
- Floating-point edge cases (subnormals, range bounds, +/- 0)
- Endianness mistakes
- Off-by-one in field offsets
- Encoding-decoding asymmetry
"""

from __future__ import annotations

import struct

import pytest
from hypothesis import given, settings
from hypothesis import strategies as st

from chemigram.core.parameterize import patch_op_params
from chemigram.core.vocab import ParameterSpec, load_packs


def _build_module_specs() -> dict[str, dict[str, tuple[ParameterSpec, str]]]:
    """For each module with parametric entries, collect parameter specs
    + a source op_params hex blob from a loaded manifest entry. Used
    to drive the property tests with realistic starting bytes (not
    synthetic baselines).

    Returns ``{module_name: {param_name: (spec, source_op_params)}}``.
    """
    vocab = load_packs(["starter", "expressive-baseline"])
    out: dict[str, dict[str, tuple[ParameterSpec, str]]] = {}
    for entry in vocab.list_all():
        if not entry.parameters:
            continue
        # Pick the plugin matching the parameter's module
        plugins_by_op = {p.operation: p for p in entry.dtstyle.plugins}
        for spec in entry.parameters:
            mod = spec.field.module
            plugin = plugins_by_op.get(mod)
            if plugin is None:
                continue
            module_specs = out.setdefault(mod, {})
            if spec.name not in module_specs:
                module_specs[spec.name] = (spec, plugin.op_params)
    return out


_MODULE_SPECS = _build_module_specs()


def _decode_field(op_params_hex: str, spec: ParameterSpec) -> float:
    """Decode the single float field at ``spec.field.offset``."""
    raw = bytes.fromhex(op_params_hex)
    offset = spec.field.offset
    if spec.field.encoding == "le_f32":
        return struct.unpack_from("<f", raw, offset)[0]
    if spec.field.encoding == "le_i32":
        return float(struct.unpack_from("<i", raw, offset)[0])
    if spec.field.encoding == "le_u32":
        return float(struct.unpack_from("<I", raw, offset)[0])
    raise NotImplementedError(f"unhandled encoding: {spec.field.encoding}")


def _pytest_param_id(mod: str, name: str) -> str:
    return f"{mod}.{name}"


# Parameters whose offset points to a field that's MODIFIED (multiplied
# / added to) rather than DIRECTLY SET. Roundtrip / idempotence don't
# apply: applying delta=+1000 doesn't write 1000 to the field, it
# scales the existing field's value by a kelvin factor; applying twice
# scales twice. Excluded from the fuzz sweep.
_DELTA_AXIS_NAMES = frozenset(
    {
        "kelvin_delta",  # temperature: scales red_coeff up, blue_coeff down
        "tint_delta",  # temperature: scales green_coeff
    }
)


def _all_params() -> list[tuple[str, str, ParameterSpec, str]]:
    """Flatten _MODULE_SPECS into a parametrize list, excluding delta
    axes whose semantics don't match the property-test invariants."""
    out: list[tuple[str, str, ParameterSpec, str]] = []
    for mod, names in _MODULE_SPECS.items():
        for name, (spec, src) in names.items():
            if name in _DELTA_AXIS_NAMES:
                continue
            out.append((mod, name, spec, src))
    return out


_PARAMETERS = _all_params()
_PARAM_IDS = [_pytest_param_id(mod, name) for mod, name, _, _ in _PARAMETERS]


@pytest.mark.parametrize("mod_name,param_name,spec,src", _PARAMETERS, ids=_PARAM_IDS)
def test_patch_roundtrip_within_declared_range(
    mod_name: str, param_name: str, spec: ParameterSpec, src: str
) -> None:
    """Property: for any value in the declared range, decoding the
    patched bytes at the field's offset recovers the patched value."""

    @given(value=st.floats(min_value=spec.range[0], max_value=spec.range[1], allow_nan=False))
    @settings(max_examples=25, deadline=None)
    def _inner(value: float) -> None:
        patched = patch_op_params(
            src, module=mod_name, modversion=spec.field.modversion, values={param_name: value}
        )
        assert patched is not None  # only temperature at identity returns None
        decoded = _decode_field(patched, spec)
        # le_f32 round-trips with ~7-digit precision; allow tolerance
        assert decoded == pytest.approx(value, rel=1e-5, abs=1e-5)

    _inner()


@pytest.mark.parametrize("mod_name,param_name,spec,src", _PARAMETERS, ids=_PARAM_IDS)
def test_patch_idempotence(mod_name: str, param_name: str, spec: ParameterSpec, src: str) -> None:
    """Property: patching twice with the same value produces the same
    bytes. Catches non-idempotent encoders (e.g., delta-style updates
    that accumulate)."""

    @given(value=st.floats(min_value=spec.range[0], max_value=spec.range[1], allow_nan=False))
    @settings(max_examples=15, deadline=None)
    def _inner(value: float) -> None:
        first = patch_op_params(
            src, module=mod_name, modversion=spec.field.modversion, values={param_name: value}
        )
        assert first is not None
        second = patch_op_params(
            first, module=mod_name, modversion=spec.field.modversion, values={param_name: value}
        )
        assert first == second

    _inner()


@pytest.mark.parametrize("mod_name,param_name,spec,src", _PARAMETERS, ids=_PARAM_IDS)
def test_patch_preserves_blob_size(
    mod_name: str, param_name: str, spec: ParameterSpec, src: str
) -> None:
    """Property: patching never changes the byte length of the
    op_params blob. Catches encoders that accidentally extend / truncate."""
    source_len = len(bytes.fromhex(src))

    @given(value=st.floats(min_value=spec.range[0], max_value=spec.range[1], allow_nan=False))
    @settings(max_examples=10, deadline=None)
    def _inner(value: float) -> None:
        patched = patch_op_params(
            src, module=mod_name, modversion=spec.field.modversion, values={param_name: value}
        )
        assert patched is not None
        assert len(bytes.fromhex(patched)) == source_len

    _inner()
